subtitle:
    2013: XIII Vanhan musiikin festivaali Imatralla 18.–23.8.2013
    2014: XIV Vanhan musiikin festivaali Imatralla 17.–20.8.2014
    2015: XV Vanhan musiikin festivaali Imatralla 16.–19.8.2015
esittely:
    2013: .
