subtitle:
    2010: X Vanhan musiikin tapahtuma Imatran kirkoissa 15.–18.8.2010
    2011: XI Vanhan musiikin tapahtuma Imatran kirkoissa 21.–24.8.2011
    2012: XII Vanhan musiikin tapahtuma Imatran kirkoissa 19.–22.8.2012
    2013: XIII Vanhan musiikin festivaali Imatralla 18.–23.8.2013
    2014: XIV Vanhan musiikin festivaali Imatralla 17.–20.8.2014
    2015: XV Vanhan musiikin festivaali Imatralla 16.–19.8.2015
    2016: XVI Vanhan musiikin festivaali Imatralla 14.–16.8.2016
    2017: XVII Vanhan musiikin festivaali Imatralla 20.–22.8.2017
    2018: XVIII Vanhan musiikin festivaali Imatralla 19.–21.8.2018
    2019: XIX Vanhan musiikin festivaali Imatralla 8.–10.9.2019
esittely:
    2011: .
    2012: .
    2019: .
esiintyjat:
    2010: .
    2013: .
    2014: .
    2015: .
    2016: .
    2017: .
    2018: .
    2019: .
ohjelma:
    2010: .
    2011: .
    2012: .
    2013: .
    2014: .
    2015: .
    2016: .
    2017: .
    2018: .
    2019: .
