subtitle:
    2006: VI Vanhan musiikin tapahtuma Imatran kirkoissa 20.–23.8.2006
    2007: VII Vanhan musiikin tapahtuma Imatran kirkoissa 12.–15.8.2007
    2008: VIII Vanhan musiikin tapahtuma Imatran kirkoissa 17.-20.8.2008
    2009: IX Vanhan musiikin tapahtuma Imatran kirkoissa 16.–19.8.2009
    2010: X Vanhan musiikin tapahtuma Imatran kirkoissa 15.–18.8.2010
    2011: XI Vanhan musiikin tapahtuma Imatran kirkoissa 21.–24.8.2011
    2012: XII Vanhan musiikin tapahtuma Imatran kirkoissa 19.–22.8.2012
    2013: XIII Vanhan musiikin festivaali Imatralla 18.–23.8.2013
    2014: XIV Vanhan musiikin festivaali Imatralla 17.–20.8.2014
    2015: XV Vanhan musiikin festivaali Imatralla 16.–19.8.2015
    2016: XVI Vanhan musiikin festivaali Imatralla 14.–16.8.2016
    2017: XVII Vanhan musiikin festivaali Imatralla 20.–22.8.2017
    2018: XVIII Vanhan musiikin festivaali Imatralla 19.–21.8.2018
    2019: XIX Vanhan musiikin festivaali Imatralla 8.–10.9.2019
    2020: Vanhan musiikin festivaali Imatralla
    2022: XX Vanhan musiikin festivaali Imatralla 4.–6.9.2022
esittely:
    2006: .
    2007: .
    2008: .
    2011: .
    2012: .
    2019: .
esiintyjat:
    2006: .
    2007: .
    2008: .
    2009: .
    2010: .
    2011: .
    2012: .
    2013: .
    2014: .
    2015: .
    2016: .
    2017: .
    2018: .
    2019: .
ohjelma:
    2006: .
    2007: .
    2008: .
    2009: .
    2010: .
    2011: .
    2012: .
    2013: .
    2014: .
    2015: .
    2016: .
    2017: .
    2018: .
    2019: .
